### ISSUE TITLE
README full upper case doc fail

### ISSUE THREAD

**Issue by Kenyo-cell** [d0rj/Meerkat#1]
In README.md says you need to write ^ - to fully transform word to upper case. but your code says u need to ^^
What do ya say, huh?
![image](https://user-images.githubusercontent.com/53817368/108590394-643c3500-7374-11eb-8bb0-923daa6f2d17.png)

**Comment by d0rj** [comment]
![image](https://user-images.githubusercontent.com/29834178/108590369-3bb43b00-7374-11eb-8e6f-851d98232d9f.png)

Readme bug fixed
